export const DOMAIN_PATTERNS = {
  'Engineering': /\b(software\s*engineer|engineering|backend|front.?end|full.?stack|developer|devops|swe\b|infrastructure|platform|distributed\s*systems?|api\s*(design|dev)|cloud|mobile\s*dev|ios\b|android|web\s*dev|coding|programming|typescript|javascript|python|java|rust|golang|c\+\+|react|node\.?js|kubernetes|microservices)\b/i,
  'Product': /\b(product\s*(manager|management|lead|director|strategy|owner|ops)|pm\b|head\s*of\s*product|vp\s*(of\s*)?product|chief\s*product|director\s*of\s*product|roadmap|go.to.market|product\s*thinking|product\s*sense)\b/i,
  'Data & ML': /\b(data\s*(scien|engineer|analyst|platform|warehouse|lake)|machine\s*learning|ml\b|artificial\s*intelligence|\bai\b|deep\s*learning|neural\s*net|llm\b|nlp\b|analytics|statistics|sql\b|big\s*data|databricks|spark|tensorflow|pytorch|computer\s*vision|generative\s*ai)\b/i,
  'Design': /\b(product\s*design|ux\b|ui\b|user\s*(experience|interface)|visual\s*design|graphic\s*design|interaction\s*design|design\s*system|figma|sketch|prototype|wireframe|brand\s*design|motion\s*design|design\s*(lead|director|manager))\b/i,
  'Startup': /\b(founder|co.?founder|startup|early.?stage|seed\s*(stage|round)?|cto\b|chief\s*(technology|technical)\s*officer|entrepreneurship|building\s*(a\s*)?(company|startup)|angel\s*investor|venture|exited|bootstrapped)\b/i,
  'UX Research': /\b(ux\s*research|user\s*research|usability(\s*testing)?|qualitative\s*research|quantitative\s*research|user\s*testing|discovery\s*research|research\s*ops|insights|ethnograph|research\s*(lead|manager|director|scientist))\b/i,
  'Healthcare': /\b(healthcare|health\s*care|medical|clinical|hospital|nursing|physician|doctor\b|dentist|dietitian|nutritionist|public\s*health|health\s*tech|patient\s*care|radiology|telehealth|mph\b|pre.?med|mcat\b|residency|usmle\b|md\b|mbbs\b|do\b\s*(school|student|degree)|pa\s*school|physician\s*assistant|clinical\s*rotation)\b/i,
  'Gaming': /\b(gaming|game\s*(dev|design|product|industry|studio|engine)|unity\b|unreal\s*engine|playstation|xbox|nintendo|esports|mobile\s*games?|live\s*service\s*game|game\s*monetization|narrative\s*design)\b/i,
  'Legal': /\b(attorney|lawyer|law\s*(school|firm|review|degree|clerk)|legal|litigation|transactional|regulatory\s*(law|counsel|affairs)|compliance|counsel|esquire|juris|jd\b|bar\s*(exam|prep|association)|biglaw|in-house|paralegal|court|contract\s*(law|review|drafting)|corporate\s*(law|counsel)|intellectual\s*property|patent|trademark|boutique\s*firm)\b/i,
  'Finance': /\b(investment\s*(bank|management|analyst)|private\s*equity|venture\s*capital|hedge\s*fund|asset\s*management|equity\s*research|cfa\b|trading|portfolio\s*(manager|management)|valuation|mergers?\s*(and\s*acquisitions?|&\s*acquisitions?)|m&a|capital\s*markets?|wealth\s*management|fintech|bloomberg|fixed\s*income|financial\s*(analyst|modeling|planning\s*&\s*analysis)|fp&a)\b/i,
  'Marketing': /\b(marketing|brand\s*(manager|strategy|marketing)|growth\s*(marketing|hacking|manager)|digital\s*marketing|content\s*(marketing|strategy)|seo\b|sem\b|paid\s*(media|acquisition|social)|demand\s*generation|product\s*marketing|public\s*relations?|pr\b|social\s*media\s*(manager|marketing)|copywriting|go.to.market\s*strategy|brand\s*awareness|influencer\s*marketing)\b/i,
  'Consulting': /\b(consulting|consultant|mckinsey|bain\b|bcg\b|deloitte|accenture|kpmg|pwc\b|ernst\s*&?\s*young|ey\b|strategy\s*&?\s*(operations?|consulting)|management\s*consulting|business\s*consulting|associate\s*consultant|engagement\s*manager|strategy\s*consultant|big\s*4\b|mbb\b)\b/i,
  'Operations': /\b(operations|biz\s*ops|business\s*operations|chief\s*of\s*staff|program\s*(manager|management)|project\s*(manager|management)|process\s*(improvement|excellence|optimization)|operational\s*excellence|ops\s*(lead|manager|director)|strategy\s*&?\s*ops|six\s*sigma|lean\s*methodology|cross.functional)\b/i,
  'Sales & Biz Dev': /\b(sales|business\s*development|biz\s*dev|account\s*(executive|manager|director)|sales\s*(engineer|manager|director|ops|strategy)|revenue\s*(operations|growth)|customer\s*success|partnerships?|enterprise\s*sales|sdr\b|bdr\b|quota|pipeline|crm\b|salesforce|solution\s*(engineer|architect|selling))\b/i,
  'Cybersecurity': /\b(cyber\s*security|cybersecurity|information\s*security|infosec|security\s*(engineer|analyst|architect|researcher|operations|clearance)|pen\s*testing|penetration\s*testing|soc\b|siem\b|ciso\b|vulnerability|malware|threat\s*(intelligence|hunting|modeling)|zero\s*trust|identity\s*(and\s*access|management)|iam\b|ethical\s*hacking|red\s*team|blue\s*team|cloud\s*security)\b/i,
  'Education': /\b(education|teaching|teacher|professor|lecturer|academic|academia|curriculum|instructional\s*design|e.learning|edtech|school\s*(counselor|administrator)|phd\b|doctorate|postdoc|tutoring|higher\s*education|faculty|k.12|classroom|school\s*district|college\s*counseling|admissions?\s*counseling|student\s*affairs)\b/i,
  'Policy & Government': /\b(policy|government|public\s*(policy|service|sector|administration)|advocacy|legislation|regulatory\s*affairs|think\s*tank|civic\s*tech|philanthropy|grant\s*(writing|management)|community\s*(organizing|development)|federal|municipal|city\s*council|state\s*(government|legislature)|foreign\s*(policy|service)|diplomacy|political\s*science|lobbyist)\b/i,
  'Nonprofit & Social Impact': /\b(non-?profit|ngo\b|social\s*(impact|enterprise|work(er)?)|case\s*(manager|work|management)|community\s*(health\s*worker|outreach|services|development)|msw\b|lcsw\b|family\s*services|youth\s*(services|work|development)|crisis\s*intervention|human\s*services|501c3|charitable|foundation|social\s*justice|equity\s*(work|advocacy))\b/i,
  'Human Resources': /\b(human\s*resources?\b|hr\b|people\s*(ops|operations|team|partner|analytics)|talent\s*(acquisition|management|development)|recruiting|recruiter|organizational\s*(development|psychology)|total\s*rewards|compensation|benefits|hrbp\b|dei\b|diversity\s*(equity|and\s*inclusion)|workforce\s*planning|employee\s*(relations|experience)|chief\s*people\s*officer|learning\s*&?\s*development)\b/i,
  'Real Estate': /\b(real\s*estate|property\s*(management|investment|development)|realty|realtor|broker|mortgage|commercial\s*(real\s*estate|property)|residential\s*(real\s*estate|property)|reit\b|proptech|urban\s*planning|land(lord|lord)?|leasing|property\s*tech|housing\s*(market|finance|policy))\b/i,
  'Accounting & Tax': /\b(accounting|accountant|cpa\b|tax\s*(professional|advisor|accountant|preparation|planning|law)|audit(ing|or)?|bookkeeping|financial\s*reporting|controller|forensic\s*accounting|managerial\s*accounting|big\s*4\s*accounting|staff\s*accountant|senior\s*accountant|tax\s*return|irs\b|gaap\b|ifrs\b)\b/i,
  'Architecture': /\b(architect(ure)?|architectural|interior\s*design(er)?|urban\s*plann|civil\s*engineering|structural\s*engineering|built\s*environment|construction\s*management|landscape\s*architect|bim\b|revit\b|autocad\b|leed\b|space\s*planning|building\s*design)\b/i,
  'Pharmacy': /\b(pharmac(y|ist|eutical)|pharmd\b|pharm\s*d|drug\s*(development|discovery|store)|clinical\s*pharmacist|retail\s*pharmacist|hospital\s*pharmacist|medication\s*(therapy|management)|compounding|pharmacy\s*(school|student|practice)|pharmaceutical\s*(industry|company|sales)|drug\s*safety)\b/i,
  'Mental Health': /\b(mental\s*health\s*(counselor|therapist|professional)|psychology|psychologist|therapist|therapy\s*(practice|license)|counseling|counselor|lcsw\b|lmft\b|licensed\s*(clinical|professional|marriage)|psychotherapy|behavioral\s*health|psychiatric|psychiatry|psychiatrist|substance\s*abuse|addiction\s*(counseling|treatment)|trauma.informed|wellness\s*coach)\b/i,
  'Media & Journalism': /\b(journalism|journalist|reporter|editor|writing|writer|content\s*(creator|writer)|media\s*(relations|communications?)|broadcast|publishing|editorial|magazine|newspaper|podcast(er|ing)?|documentary|storytelling|communications?\s*(director|manager|specialist)|public\s*affairs|screenwriting|film\s*(maker|production|director)|video\s*production|animation|animator)\b/i,
  'Supply Chain': /\b(supply\s*chain|logistics|procurement|sourcing|inventory\s*management|warehouse|fulfillment|distribution|demand\s*planning|vendor\s*management|scm\b|erp\b|sap\b|last\s*mile|freight|transportation|import\s*(export|\s*customs)|manufacturing|operations\s*(planning|research)|production\s*planning)\b/i,
  'Climate & Sustainability': /\b(climate|sustainability|clean\s*(energy|tech)|renewable\s*energy|solar|wind\s*energy|environmental|esg\b|carbon\s*(footprint|neutral|offset)|green\s*tech|energy\s*(transition|storage|efficiency)|sustainability\s*(manager|officer|consultant)|environmental\s*(engineer|scientist|policy)|impact\s*investing|net\s*zero|decarbonization)\b/i,
}

export function parseDomains(text) {
  const matched = []
  for (const [domain, pattern] of Object.entries(DOMAIN_PATTERNS)) {
    if (pattern.test(text)) matched.push(domain)
  }
  return matched
}
